### PR TITLE
Bleeding edge

### PR DESCRIPTION
**Pull request by alien999999999**
Ok, so i updated the different language stuff, and figured out that Set.addAll() does not actually exist, and rewrote it a bit.

I found out how to run it, and i've seen updated playercount, but not the "last player" and the start button doesn't actually re-enable to be able to try and start it...

### CODE REVIEW

**Comment by alien999999999** [comment]
OK, so i got it to run, with these fixes, but in the 3rd round, outAnswer was undefined (in function perPPJudgement").

(I was running with 2 players)

Also, questions and ideas:
- is it useful to have language per user and answer? wouldn't it just be easier to decide from server which language the whole thing runs on? or are you gonna translate all the stuff, and then people see what answer was in what language? kinda strange, but maybe?
- in current times, i would like to use this with a bunch of kids that are "socially distant"; which means:
- would not be able to rely on seeing the TV screen, or not all of them anyway, unless we can get some of that stuff over?
- would need to limit the number of people that provide answers?
- thus maybe would need to have people answer if they want to spectate only(but vote or not?) or wanting to be chosen.
- then, out of the number of people who want to answer, a fixed number (setting?) could be chosen, and they are the players, the rest just vote.
- also, timers, like, instead of "run the game" , just have the game start X seconds after 2 or more players have joined; then still allow joining with voting until the voting starts.
- nice to have : some kind of percentage/animation, on how far each player has answered the questions... (maybe even show a random answer for a random question on screen, without the question; as a teaser)
- configurable nr of rounds, type, and how many questions per round?

This could allow like the whole class to join in from anywhere (don't worry about happyfuntimes, i'm not using it, i'm going directly, and i can put that on one of my subdomains and thus have outside people join in too) but that's just for me to figure out...

WDYT?

**Comment by pucgenie** [comment]
I wasn't able to continue where I left off so I'm a bit lost in my own code changes, lol. I remember I've been trying to allow suddenly-disconnected players to reconnect - I think it was working in bleeding-edge. However, as you discovered multible issues in the most baic things, I don't trust my own memory anymore.

The language-per-user things should aid text-to-speech. I used a catalogue consisting of English text and most of the players wanted to answer in German. It was a bit boring to just read txt off the screen so I wanted to add TTS. Because of a bug (or "feature") in WebKit/Chromium I stopped working on this project.

That's great that you want to use this game for "bridging" the kids :)

It's not that hard but time-consuming to send the whole game state (what needs to be shown) to each client and render it.

"would need to limit the number of people that provide answers" - I don't get what you mean exactly. I wanted to clone the original ruleset of a certain game on which this clone is based on.

Spectator mode shouldn' be too hard to implement. In the original game, that's possible, too.

I don't know what timings would work best.

Graphical design/layout is something I'm afraid I can't add much to (Teaser: Like in the original game xD ).

I wanted to create an abstract engine for two similar games, so yes, let's implements many configuration options!

I can confirm that direct connections are working.

Sadly I wasn't able to find out how to add an issue tracker to this repository/project, so I'll slowly add all features somewhere in "Projects".

**Comment by alien999999999** [comment]
i guess that's a good idea, for features:

about timers, you can avoid your problems by just having more configurations :-)

about sending game state, we could maybe use game.html for spectators basically, if we can seperate the game server from the layout (which would also make it possible to run without tv even, maybe in the distant future; i also saw the textbased clients, i like your thinking; i'm also not good graphically, so i also don't quite care much about it; i saw you did some kind of resource pack which does like audio and video, good stuff.

i understand now why you want TTS, so you don't really have to translate all the questions... :-)

I think i'm gonna change the roundlogics a bit so its more configurable; and i've been thinking of creating it with some more constants, so that doesn't change and you don't have to request the interfaceobj (helps for seperation). I hope in this way i can fix the round_3 thing, which may have been looking for 2 answers which it doesn't seem that way... btw: it would be great to have some version of the Config so i can extend it and improve on it.

after that, i think i'm gonna try and ask the people if they want to answer questions or only vote.

or maybe first have a max limit of answerable-players and just randomly select from the people (if there are more than 4 for example) so you don't have like 20 answers to choose from.

**Comment by pucgenie** [comment]
I wanted to implement "the secret config" to not be mandatory at all.
On my machine it uses the resource pack of the original game - if you ever wondered why the data structures are more complex than wyatt's, this is the reason.

File: secrets/QuiplibreConfig.js
-----
```
"use strict";
/**
 * non-public
**/
QuiplibreConfig.enhanced = true
QuiplibreConfig.resourceBase = '../secrets/Quiplash'
QuiplibreConfig.theResPack =  `${QuiplibreConfig.resourceBase}/content/QuiplashQuestion`
QuiplibreConfig.dataFileExtension = 'jet'
QuiplibreConfig.resPackLang = 'en'
QuiplibreConfig.secretHintergrundmusik = '../secrets/Quiplash/TalkshowExport/project/media/78614.mp3'
QuiplibreConfig.secretTitelvideo = '../secrets/quiplashxl.mp4'
QuiplibreConfig.dataFileName = `/data.${QuiplibreConfig.dataFileExtension}`
```

**Pull request merged**
